name = "61craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a361bf1f96601b24b9d46c91e3e456c20ee3e1f917f7310fb7da83dcd7d4fd9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
