name = "61craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6cac887eb4938af32b6db6682a91c324778988a4b2b60337e7b36af88746d82"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
