name = "61craft"
author = "Aikoyori"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d52ef12f7be20b195242f87999164667a7deb2415786efa22b482b3cca9c9648"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
